name: build_orm_packages
on:
  push:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r -j orm_stack_private_dns.zip . -i infrastructure/*.tf infrastructure/*.yml
      - uses: actions/upload-artifact@v2
        with:
          name: orm_stack_private_dns.zip
